<?php
namespace ESNP_Kit\Widgets;

use Elementor\Widget_Base;
use Elementor\Controls_Manager;
use Elementor\Repeater;

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

/**
 * Appointment Booking Widget
 */
class Booking_Widget extends Widget_Base
{

    public function get_name()
    {
        return 'esnp-booking';
    }

    public function get_title()
    {
        return esc_html__('Appointment Booking Pro', 'esnp-kit');
    }

    public function get_icon()
    {
        return 'eicon-calendar';
    }

    public function get_categories()
    {
        return ['esnp-kit'];
    }

    protected function register_controls()
    {

        $this->start_controls_section(
            'section_booking',
            [
                'label' => esc_html__('Booking Settings', 'esnp-kit'),
            ]
        );

        $this->add_control(
            'available_days',
            [
                'label' => esc_html__('Available Days', 'esnp-kit'),
                'type' => Controls_Manager::SELECT2,
                'multiple' => true,
                'options' => [
                    '1' => 'Monday',
                    '2' => 'Tuesday',
                    '3' => 'Wednesday',
                    '4' => 'Thursday',
                    '5' => 'Friday',
                    '6' => 'Saturday',
                    '0' => 'Sunday',
                ],
                'default' => ['1', '2', '3', '4', '5'],
            ]
        );

        $repeater = new Repeater();

        $repeater->add_control(
            'slot_time',
            [
                'label' => esc_html__('Time Slot', 'esnp-kit'),
                'type' => Controls_Manager::TEXT,
                'placeholder' => '09:00',
            ]
        );

        $this->add_control(
            'time_slots',
            [
                'label' => esc_html__('Available Slots', 'esnp-kit'),
                'type' => Controls_Manager::REPEATER,
                'fields' => $repeater->get_controls(),
                'default' => [
                    ['slot_time' => '09:00'],
                    ['slot_time' => '10:00'],
                    ['slot_time' => '11:00'],
                    ['slot_time' => '13:00'],
                    ['slot_time' => '14:00'],
                    ['slot_time' => '15:00'],
                ],
                'title_field' => '{{{ slot_time }}}',
            ]
        );

        $this->end_controls_section();

        $this->start_controls_section(
            'section_style_booking',
            [
                'label' => esc_html__('Style', 'esnp-kit'),
                'tab' => Controls_Manager::TAB_STYLE,
            ]
        );

        $this->add_control(
            'accent_color',
            [
                'label' => esc_html__('Accent Color', 'esnp-kit'),
                'type' => Controls_Manager::COLOR,
                'selectors' => [
                    '{{WRAPPER}} .esnp-booking-day.esnp-is-selected' => 'background-color: {{VALUE}};',
                    '{{WRAPPER}} .esnp-booking-slot.esnp-is-selected' => 'border-color: {{VALUE}}; color: {{VALUE}};',
                    '{{WRAPPER}} .esnp-booking-submit' => 'background-color: {{VALUE}};',
                ],
            ]
        );

        $this->end_controls_section();
    }

    protected function render()
    {
        $settings = $this->get_settings_for_display();
        $id = $this->get_id();
        ?>
        <div class="esnp-booking-container" id="esnp-booking-<?php echo esc_attr($id); ?>">
            <div class="esnp-booking-calendar">
                <div class="esnp-calendar-header">
                    <button class="esnp-calendar-prev"><i class="fas fa-chevron-left"></i></button>
                    <h4 class="esnp-calendar-month">Month Year</h4>
                    <button class="esnp-calendar-next"><i class="fas fa-chevron-right"></i></button>
                </div>
                <div class="esnp-calendar-grid">
                    <!-- Generated by JS -->
                </div>
            </div>

            <div class="esnp-booking-slots-wrapper" style="display: none;">
                <h5 class="esnp-slots-title">
                    <?php esc_html_e('Select an available time', 'esnp-kit'); ?>
                </h5>
                <div class="esnp-booking-slots">
                    <?php foreach ($settings['time_slots'] as $slot): ?>
                        <button class="esnp-booking-slot" data-time="<?php echo esc_attr($slot['slot_time']); ?>">
                            <?php echo esc_html($slot['slot_time']); ?>
                        </button>
                    <?php endforeach; ?>
                </div>
            </div>

            <div class="esnp-booking-form" style="display: none;">
                <input type="text" class="esnp-booking-name" placeholder="<?php esc_attr_e('Your Name', 'esnp-kit'); ?>"
                    required>
                <input type="email" class="esnp-booking-email" placeholder="<?php esc_attr_e('Your Email', 'esnp-kit'); ?>"
                    required>
                <button class="esnp-booking-submit">
                    <?php esc_html_e('Confirm Booking', 'esnp-kit'); ?>
                </button>
            </div>

            <div class="esnp-booking-message"></div>
        </div>
        <?php
    }
}
